- type: web
    name: zoomtrip-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview  # "npm start"-ku pathila "npm run preview"