services:
  - type: web
    name: zoomtrip-backend
    runtime: dotnet
    plan: free
    rootDir: backend
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/ZoomTrip.dll

  - type: web
    name: zoomtrip-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start