services:
  - type: web
    name: zoomtrip-backend
    runtime: docker # Inga 'dotnet' thookitu 'docker' nu mathirukkom
    plan: free
    rootDir: backend

  - type: web
    name: zoomtrip-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start